### ISSUE TITLE
Warnings displayed when pipeline runs

### ISSUE THREAD

**Issue by fudgefactor** [WIFIS-Team/pipeline#2]
The following warnings are seen when running the full data reduction pipeline on Monster:
1. WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/usr/lib/python2.7/dist-packages/astropy/coordinates/angle_lextab.py'
2. WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/usr/lib/python2.7/dist-packages/astropy/coordinates/angle_parsetab.py'
3. *** WARNING: Only astropy version > 2 supports radial velocity corrections, no corrections computed ***
The reduced data still looks good so it is unclear if these warnings have any impact.

**Comment by jgrunhut** [comment]
First two warnings seem to be an issue with your astropy installation.
Last warning is, as stated, you have astropy < 2. Therefore, no radial velocity corrections (in this case Barycentric corrections) were computed and corrected for.
